# Baseline eğitim konfigürasyonu
pseudo_labels_csv: "data/pseudo_labels.csv"
train_series_csv: "/kaggle/input/competitions/rsna-knee-abnormality-detection/train_series.csv"
series_root: "/kaggle/input/competitions/rsna-knee-abnormality-detection/train_series"
output_dir: "/kaggle/working/outputs"

backbone: "efficientnet_b0"
target_slices: 12
resize_to: 192

batch_size: 1
num_workers: 2
lr: 0.00007
weight_decay: 0.00001
epochs: 20
n_folds: 5
seed: 42
